// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: camera.proto

#include "camera.pb.h"
#include "camera.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace camera {

static const char* CameraService_method_names[] = {
  "/camera.CameraService/StreamFrames",
};

std::unique_ptr< CameraService::Stub> CameraService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< CameraService::Stub> stub(new CameraService::Stub(channel, options));
  return stub;
}

CameraService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_StreamFrames_(CameraService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  {}

::grpc::ClientReader< ::camera::CameraFrame>* CameraService::Stub::StreamFramesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request) {
  return ::grpc::internal::ClientReaderFactory< ::camera::CameraFrame>::Create(channel_.get(), rpcmethod_StreamFrames_, context, request);
}

void CameraService::Stub::async::StreamFrames(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::grpc::ClientReadReactor< ::camera::CameraFrame>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::camera::CameraFrame>::Create(stub_->channel_.get(), stub_->rpcmethod_StreamFrames_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::camera::CameraFrame>* CameraService::Stub::AsyncStreamFramesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::camera::CameraFrame>::Create(channel_.get(), cq, rpcmethod_StreamFrames_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::camera::CameraFrame>* CameraService::Stub::PrepareAsyncStreamFramesRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::camera::CameraFrame>::Create(channel_.get(), cq, rpcmethod_StreamFrames_, context, request, false, nullptr);
}

CameraService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      CameraService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< CameraService::Service, ::google::protobuf::Empty, ::camera::CameraFrame>(
          [](CameraService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::grpc::ServerWriter<::camera::CameraFrame>* writer) {
               return service->StreamFrames(ctx, req, writer);
             }, this)));
}

CameraService::Service::~Service() {
}

::grpc::Status CameraService::Service::StreamFrames(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::grpc::ServerWriter< ::camera::CameraFrame>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace camera

