// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: camera.proto
// Protobuf C++ Version: 5.27.2

#ifndef GOOGLE_PROTOBUF_INCLUDED_camera_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_camera_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5027002
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/empty.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_camera_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_camera_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_camera_2eproto;
namespace camera {
class CameraFrame;
struct CameraFrameDefaultTypeInternal;
extern CameraFrameDefaultTypeInternal _CameraFrame_default_instance_;
}  // namespace camera
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace camera {

// ===================================================================


// -------------------------------------------------------------------

class CameraFrame final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:camera.CameraFrame) */ {
 public:
  inline CameraFrame() : CameraFrame(nullptr) {}
  ~CameraFrame() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CameraFrame(
      ::google::protobuf::internal::ConstantInitialized);

  inline CameraFrame(const CameraFrame& from) : CameraFrame(nullptr, from) {}
  inline CameraFrame(CameraFrame&& from) noexcept
      : CameraFrame(nullptr, std::move(from)) {}
  inline CameraFrame& operator=(const CameraFrame& from) {
    CopyFrom(from);
    return *this;
  }
  inline CameraFrame& operator=(CameraFrame&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CameraFrame& default_instance() {
    return *internal_default_instance();
  }
  static inline const CameraFrame* internal_default_instance() {
    return reinterpret_cast<const CameraFrame*>(
        &_CameraFrame_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CameraFrame& a, CameraFrame& b) { a.Swap(&b); }
  inline void Swap(CameraFrame* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CameraFrame* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CameraFrame* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<CameraFrame>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CameraFrame& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CameraFrame& from) { CameraFrame::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(CameraFrame* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "camera.CameraFrame"; }

 protected:
  explicit CameraFrame(::google::protobuf::Arena* arena);
  CameraFrame(::google::protobuf::Arena* arena, const CameraFrame& from);
  CameraFrame(::google::protobuf::Arena* arena, CameraFrame&& from) noexcept
      : CameraFrame(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::Message::ClassData* GetClassData() const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSlaveImageFieldNumber = 1,
    kWidthFieldNumber = 2,
    kHeightFieldNumber = 3,
  };
  // bytes slave_image = 1;
  void clear_slave_image() ;
  const std::string& slave_image() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_slave_image(Arg_&& arg, Args_... args);
  std::string* mutable_slave_image();
  PROTOBUF_NODISCARD std::string* release_slave_image();
  void set_allocated_slave_image(std::string* value);

  private:
  const std::string& _internal_slave_image() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_slave_image(
      const std::string& value);
  std::string* _internal_mutable_slave_image();

  public:
  // uint32 width = 2;
  void clear_width() ;
  ::uint32_t width() const;
  void set_width(::uint32_t value);

  private:
  ::uint32_t _internal_width() const;
  void _internal_set_width(::uint32_t value);

  public:
  // uint32 height = 3;
  void clear_height() ;
  ::uint32_t height() const;
  void set_height(::uint32_t value);

  private:
  ::uint32_t _internal_height() const;
  void _internal_set_height(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:camera.CameraFrame)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  static constexpr const void* _raw_default_instance_ =
      &_CameraFrame_default_instance_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const CameraFrame& from_msg);
    ::google::protobuf::internal::ArenaStringPtr slave_image_;
    ::uint32_t width_;
    ::uint32_t height_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_camera_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CameraFrame

// bytes slave_image = 1;
inline void CameraFrame::clear_slave_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slave_image_.ClearToEmpty();
}
inline const std::string& CameraFrame::slave_image() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:camera.CameraFrame.slave_image)
  return _internal_slave_image();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void CameraFrame::set_slave_image(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slave_image_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:camera.CameraFrame.slave_image)
}
inline std::string* CameraFrame::mutable_slave_image() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_slave_image();
  // @@protoc_insertion_point(field_mutable:camera.CameraFrame.slave_image)
  return _s;
}
inline const std::string& CameraFrame::_internal_slave_image() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.slave_image_.Get();
}
inline void CameraFrame::_internal_set_slave_image(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slave_image_.Set(value, GetArena());
}
inline std::string* CameraFrame::_internal_mutable_slave_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.slave_image_.Mutable( GetArena());
}
inline std::string* CameraFrame::release_slave_image() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:camera.CameraFrame.slave_image)
  return _impl_.slave_image_.Release();
}
inline void CameraFrame::set_allocated_slave_image(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.slave_image_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.slave_image_.IsDefault()) {
          _impl_.slave_image_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:camera.CameraFrame.slave_image)
}

// uint32 width = 2;
inline void CameraFrame::clear_width() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = 0u;
}
inline ::uint32_t CameraFrame::width() const {
  // @@protoc_insertion_point(field_get:camera.CameraFrame.width)
  return _internal_width();
}
inline void CameraFrame::set_width(::uint32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:camera.CameraFrame.width)
}
inline ::uint32_t CameraFrame::_internal_width() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.width_;
}
inline void CameraFrame::_internal_set_width(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.width_ = value;
}

// uint32 height = 3;
inline void CameraFrame::clear_height() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = 0u;
}
inline ::uint32_t CameraFrame::height() const {
  // @@protoc_insertion_point(field_get:camera.CameraFrame.height)
  return _internal_height();
}
inline void CameraFrame::set_height(::uint32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:camera.CameraFrame.height)
}
inline ::uint32_t CameraFrame::_internal_height() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.height_;
}
inline void CameraFrame::_internal_set_height(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.height_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace camera


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_camera_2eproto_2epb_2eh
